name: Deploy to Hostinger Shared Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to Hostinger Shared Server
        uses: appleboy/scp-action@master
        with:
          host: 217.21.94.205
          username: u790439483
          password: Rammandir@2021
          port: 65002
          source: dist/
          target: public_html/public_html

